name: breadcrumbs
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.4
  geolocator: ^11.1.0
  permission_handler: ^11.3.1
  http: ^1.2.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  firebase_auth: 5.7.0
  google_sign_in: ^6.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true